spring:
  datasource:
    url: jdbc:mysql://localhost/plan
    #    url: jdbc:h2:mem:test
    username: root
    password: Duck9962@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
#  org.hibernate: trace
  org.hibernate.SQL: debug
  org.hibernate.type: trace